### ISSUE TITLE
Index out of bounds if bad header exactly matching "Bearer "

### ISSUE THREAD

**Issue by tgkprog** [sveri/spring-boot-template#1]
i would check length too spring-boot-template/src/main/java/de/sveri/cleanercomm/filter/JwtFilter.java

   `if (authHeader == null || !authHeader.startsWith("Bearer "))`

so final String token = authHeader.substring(7); // The part after "Bearer " does not lead to a index out of bounds error. In the off case that you get a ibad header exactly matching "Bearer "

**Comment by sveri** [comment]
Hi,

I am not sure what you mean exactly? I added a test: https://github.com/sveri/spring-boot-template/commit/d2911077483c4eb8132ecd78f99e1506263cf0a1 that submits only "Bearer " as the token, without the actual toke and it fails as expected.
Was that what you meant? Or something different?

**Comment by tgkprog** [comment]
that is fine if you want it to test. i would add code like : 

```
if (authHeader == null || !authHeader.startsWith("Bearer ") || authHeader.length() < 8) {
    log.error("Missing or invalid Authorization header."); //...
```

In https://github.com/sveri/spring-boot-template/blob/master/src/main/java/de/sveri/cleanercomm/filter/JwtFilter.java

**Comment by sveri** [comment]
@tgkprog 

I mean I created a test that replays your scenario and the application behaves like expected. It will throw an error about the token being wrong, which is enough I think. 
The only advantage I see in your case is a better error message, not sure if thats worth  a few more lines of code.
